services:
    pml.exception:
        class: '%pml_exception.class%'
        arguments:
            templateEngine: "@templating"
            kernel: "@kernel"
            layout: "%pml_exception.layout%"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
