services:
    pml.exception:
        class: '%pml_exception.class%'
        arguments:
            - "@templating"
            - "@kernel"
            - "%pml_exception.layout%"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
